---
vlans:
  - id: 100
    name: web_servers

interfaces_l2:
  - name: gi0/1
    mode: trunk
    access_vlan: null
    trunk_allowed_vlans: 1-4094
    state: present
  - name: gi0/3
    mode: access
    access_vlan: 100
    trunk_allowed_vlans: null
    state: present
