---
vlans:
  - id: 102
    name: web_servers

interfaces_l2:
  - name: eth1/1
    mode: trunk
    trunk_allowed_vlans: 1-4094
    state: present
  - name: eth1/4
    mode: trunk
    trunk_allowed_vlans: 1-4094
    state: present

interfaces_l3:
  - name: Vlan102
    ipv4: 192.168.2.100/24
