---
- name: Configure SNMPv3
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
    - name: Configure SNMP User
      nxos_snmp_user:
         user: "{{ item.user }}"
         authentication: "{{ item.auth }}"
         encrypt: "{{ item.encrypt }}"
         privacy: "{{ item.privacy }}"
         pwd: "{{ item.pwd }}"
      with_items: "{{ snmp_users }}"


